packages:
  - auth-connect/*
  - identity-vault/*
  - demos/*
allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  lmdb: true
  msgpackr-extract: true
  sharp: true
patchedDependencies:
  '@ionic-enterprise/secure-storage@3.1.0': patches/@ionic-enterprise__secure-storage@3.1.0.patch
